/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-2',
  aws_appsync_graphqlEndpoint:
    'https://jhvw5lfvgjh2vgk6ux52rmuj2e.appsync-api.us-east-2.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-2',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-l2fql3pm75dk7iv7w745vzxyiq',
  aws_cognito_identity_pool_id:
    'us-east-2:251159db-75bd-44a2-9ac4-14fa2045668b',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_flOx4jyCl',
  aws_user_pools_web_client_id: '464jddl50dl0fkgig8bhighfk0',
  oauth: {},
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: [],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_user_files_s3_bucket: 'ferrari-storage153848-staging',
  aws_user_files_s3_bucket_region: 'us-east-2',
  region: 'us-east-2',
};

export default awsmobile;
